apiVersion: v1
kind: PersistentVolume
metadata:
 name: dockerfile
 labels:
   type: local
spec:
 capacity:
   storage: 20Mi
 accessModes:
   - ReadWriteOnce
 storageClassName: standard
 hostPath:
   path: "/home/mohit/kaniko"
